// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentEduProject.DataClass;

#nullable disable

namespace StudentEduApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("StudentEduApp.DataClass.EgitimKayit", b =>
                {
                    b.Property<int>("KayitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EgitimModulId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModulId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("KayitId");

                    b.HasIndex("EgitimModulId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("EgitimKayitlari");
                });

            modelBuilder.Entity("StudentEduApp.DataClass.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .HasColumnType("TEXT");

                    b.Property<string>("AktiflikDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bolum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("StudentEduProject.DataClass.EgitimModul", b =>
                {
                    b.Property<int>("EgitimModulId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModulAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seviye")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sure")
                        .HasColumnType("INTEGER");

                    b.HasKey("EgitimModulId");

                    b.ToTable("EgitimModulleri");
                });

            modelBuilder.Entity("StudentEduProject.DataClass.Performans", b =>
                {
                    b.Property<int>("PerformansId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasariSeviyesi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevamYuzdesi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrtalamaNot")
                        .HasColumnType("INTEGER");

                    b.HasKey("PerformansId");

                    b.ToTable("Performanslar");
                });

            modelBuilder.Entity("StudentEduApp.DataClass.EgitimKayit", b =>
                {
                    b.HasOne("StudentEduProject.DataClass.EgitimModul", "EgitimModul")
                        .WithMany()
                        .HasForeignKey("EgitimModulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentEduApp.DataClass.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EgitimModul");

                    b.Navigation("Ogrenci");
                });
#pragma warning restore 612, 618
        }
    }
}
